### ISSUE TITLE
omakase mode fails during build

### ISSUE THREAD

**Issue by terlar** [eagletmt/guzuta#1]
```
$ env RUST_BACKTRACE=1 guzuta omakase build cower
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 2, message: "No such file or directory" } })', src/libcore/result.rs:868
stack backtrace:
   1:     0x556e205b2aac - <unknown>
   2:     0x556e205ba3ce - <unknown>
   3:     0x556e205b9fca - <unknown>
   4:     0x556e205ba86b - <unknown>
   5:     0x556e205ba704 - <unknown>
   6:     0x556e205ba629 - <unknown>
   7:     0x556e205ba5b7 - <unknown>
   8:     0x556e20606f2d - <unknown>
   9:     0x556e203e6032 - <unknown>
  10:     0x556e204041a8 - <unknown>
  11:     0x556e203f8c42 - <unknown>
  12:     0x556e203f8188 - <unknown>
  13:     0x556e205c176a - <unknown>
  14:     0x556e205bafd6 - <unknown>
  15:     0x7f27a07c0510 - __libc_start_main
  16:     0x556e203bb5f9 - <unknown>
  17:                0x0 - <unknown>
```

I get the following error trying to build any package, not sure what could be wrong, which directory is the missing one at this point?

I followed the instructions under the omakase section.

This looks promising, looking forward to use it :+1:

**Comment by eagletmt** [comment]
Could you show me your `.guzuta.yml` file?

The backtrace information is less informative. Could you install with `--debug` and show me the backtrace again?
(Of course, error messages should be improved... sorry)

**Comment by eagletmt** [comment]
I've released v0.2.4 which improves error messages.
Please try `cargo install guzuta --debug --vers 0.2.4 --force`.

**Comment by terlar** [comment]
No problem, I hope I can help out finding this issue.

This was a slight improvement, so it seems it might be the S3 files that are missing? But I wanted to start using this so I guess I shouldn't need to upload stuff first.

```
thread 'main' panicked at 'Unable to download files from S3: Io(Error { repr: Os { code: 2, message: "No such file or directory" } })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x5563c2cf6d1c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5563c2cfe5ce - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5563c2cfe1d4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x5563c2cfea6b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5563c2cfe904 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5563c2cfe829 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x5563c2cfe7b7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x5563c2d2adcd - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x5563c253f0d5 - core::result::unwrap_failed::hd763ff9d2cb6efd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x5563c2527ef2 - <core::result::Result<T, E>>::expect::h4b745c8718b9716e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:769
  11:     0x5563c25a5326 - guzuta::omakase_build::hdc18f01d6ef1165a
                        at /home/terje/.cargo/registry/src/github.com-1ecc6299db9ec823/guzuta-0.2.4/src/main.rs:340
  12:     0x5563c25a13e9 - guzuta::run_subcommand::hcea1e1ab831992f4
                        at /home/terje/.cargo/registry/src/github.com-1ecc6299db9ec823/guzuta-0.2.4/src/main.rs:169
  13:     0x5563c25a08fe - guzuta::main::h8d955dcf123a3dca
                        at /home/terje/.cargo/registry/src/github.com-1ecc6299db9ec823/guzuta-0.2.4/src/main.rs:142
  14:     0x5563c2d059da - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x5563c2cff1d6 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  16:     0x5563c25a7ae2 - main
  17:     0x7f3b8910f510 - __libc_start_main
  18:     0x5563c24adce9 - _start
  19:                0x0 - <unknown>
```

The `.guzuta.yml` looks like this:
```
name: yak
package_key: 89AF679B037E1D2A
repo_key: 89AF679B037E1D2A
srcdest: sources
logdest: logs
pkgbuild: base
builds:
  x86_64:
    chroot: /var/cache/guzuta/chroot-x86_64
s3:
  bucket: yak-packages
  region: eu-central-1
```

**Comment by eagletmt** [comment]
Fixed in master https://github.com/eagletmt/guzuta/commit/5f1290325577634fd8fe80244951db49f24fc424 .
As a workaround, you can avoid the error by `mkdir -p sources logs yak/os/x86_64`.

There's a bad news for S3 backend: Rusoto v0.23.0 and v0.23.1 cannot download files from S3: https://github.com/rusoto/rusoto/pull/569 .
You can use guzuta with S3 by checking out v0.2.1.

```
% git checkout v0.2.1
% cargo install --locked --force --debug
% guzuta --version
guzuta 0.2.1
```

**Comment by eagletmt** [comment]
> You can use guzuta with S3 by checking out v0.2.1.

Or, you can also use master. It uses the latest (unreleased) version of Rusoto.
https://github.com/eagletmt/guzuta/commit/d40e9eea65fa16d3566e1c866a00c48c5a3ffbc7
